# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.27.6/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.27.6/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/jingxi_yu/Downloads/distributed/miniraft-cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/jingxi_yu/Downloads/distributed/miniraft-cpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/opt/homebrew/Cellar/cmake/3.27.6/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.27.6/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.27.6/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jingxi_yu/Downloads/distributed/miniraft-cpp/CMakeFiles /Users/jingxi_yu/Downloads/distributed/miniraft-cpp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jingxi_yu/Downloads/distributed/miniraft-cpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named miniraft

# Build rule for target.
miniraft: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 miniraft
.PHONY : miniraft

# fast build rule for target.
miniraft/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniraft.dir/build.make CMakeFiles/miniraft.dir/build
.PHONY : miniraft/fast

#=============================================================================
# Target rules for targets named test_raft

# Build rule for target.
test_raft: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_raft
.PHONY : test_raft

# fast build rule for target.
test_raft/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_raft.dir/build.make CMakeFiles/test_raft.dir/build
.PHONY : test_raft/fast

#=============================================================================
# Target rules for targets named test_read_write

# Build rule for target.
test_read_write: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_read_write
.PHONY : test_read_write

# fast build rule for target.
test_read_write/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_read_write.dir/build.make CMakeFiles/test_read_write.dir/build
.PHONY : test_read_write/fast

#=============================================================================
# Target rules for targets named server

# Build rule for target.
server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 server
.PHONY : server

# fast build rule for target.
server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/build
.PHONY : server/fast

#=============================================================================
# Target rules for targets named client

# Build rule for target.
client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 client
.PHONY : client

# fast build rule for target.
client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/build
.PHONY : client/fast

#=============================================================================
# Target rules for targets named kv

# Build rule for target.
kv: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kv
.PHONY : kv

# fast build rule for target.
kv/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kv.dir/build.make CMakeFiles/kv.dir/build
.PHONY : kv/fast

#=============================================================================
# Target rules for targets named coroio

# Build rule for target.
coroio: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 coroio
.PHONY : coroio

# fast build rule for target.
coroio/fast:
	$(MAKE) $(MAKESILENT) -f coroio/CMakeFiles/coroio.dir/build.make coroio/CMakeFiles/coroio.dir/build
.PHONY : coroio/fast

#=============================================================================
# Target rules for targets named timers

# Build rule for target.
timers: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 timers
.PHONY : timers

# fast build rule for target.
timers/fast:
	$(MAKE) $(MAKESILENT) -f coroio/CMakeFiles/timers.dir/build.make coroio/CMakeFiles/timers.dir/build
.PHONY : timers/fast

#=============================================================================
# Target rules for targets named echotest

# Build rule for target.
echotest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 echotest
.PHONY : echotest

# fast build rule for target.
echotest/fast:
	$(MAKE) $(MAKESILENT) -f coroio/CMakeFiles/echotest.dir/build.make coroio/CMakeFiles/echotest.dir/build
.PHONY : echotest/fast

#=============================================================================
# Target rules for targets named echoserver

# Build rule for target.
echoserver: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 echoserver
.PHONY : echoserver

# fast build rule for target.
echoserver/fast:
	$(MAKE) $(MAKESILENT) -f coroio/CMakeFiles/echoserver.dir/build.make coroio/CMakeFiles/echoserver.dir/build
.PHONY : echoserver/fast

#=============================================================================
# Target rules for targets named echoclient

# Build rule for target.
echoclient: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 echoclient
.PHONY : echoclient

# fast build rule for target.
echoclient/fast:
	$(MAKE) $(MAKESILENT) -f coroio/CMakeFiles/echoclient.dir/build.make coroio/CMakeFiles/echoclient.dir/build
.PHONY : echoclient/fast

#=============================================================================
# Target rules for targets named sslechoclient

# Build rule for target.
sslechoclient: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sslechoclient
.PHONY : sslechoclient

# fast build rule for target.
sslechoclient/fast:
	$(MAKE) $(MAKESILENT) -f coroio/CMakeFiles/sslechoclient.dir/build.make coroio/CMakeFiles/sslechoclient.dir/build
.PHONY : sslechoclient/fast

#=============================================================================
# Target rules for targets named sslechoserver

# Build rule for target.
sslechoserver: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sslechoserver
.PHONY : sslechoserver

# fast build rule for target.
sslechoserver/fast:
	$(MAKE) $(MAKESILENT) -f coroio/CMakeFiles/sslechoserver.dir/build.make coroio/CMakeFiles/sslechoserver.dir/build
.PHONY : sslechoserver/fast

#=============================================================================
# Target rules for targets named resolver

# Build rule for target.
resolver: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 resolver
.PHONY : resolver

# fast build rule for target.
resolver/fast:
	$(MAKE) $(MAKESILENT) -f coroio/CMakeFiles/resolver.dir/build.make coroio/CMakeFiles/resolver.dir/build
.PHONY : resolver/fast

#=============================================================================
# Target rules for targets named bench

# Build rule for target.
bench: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bench
.PHONY : bench

# fast build rule for target.
bench/fast:
	$(MAKE) $(MAKESILENT) -f coroio/CMakeFiles/bench.dir/build.make coroio/CMakeFiles/bench.dir/build
.PHONY : bench/fast

#=============================================================================
# Target rules for targets named ut_tests

# Build rule for target.
ut_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ut_tests
.PHONY : ut_tests

# fast build rule for target.
ut_tests/fast:
	$(MAKE) $(MAKESILENT) -f coroio/CMakeFiles/ut_tests.dir/build.make coroio/CMakeFiles/ut_tests.dir/build
.PHONY : ut_tests/fast

client/client.o: client/client.cpp.o
.PHONY : client/client.o

# target to build an object file
client/client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/client/client.cpp.o
.PHONY : client/client.cpp.o

client/client.i: client/client.cpp.i
.PHONY : client/client.i

# target to preprocess a source file
client/client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/client/client.cpp.i
.PHONY : client/client.cpp.i

client/client.s: client/client.cpp.s
.PHONY : client/client.s

# target to generate assembly for a file
client/client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/client/client.cpp.s
.PHONY : client/client.cpp.s

examples/kv.o: examples/kv.cpp.o
.PHONY : examples/kv.o

# target to build an object file
examples/kv.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kv.dir/build.make CMakeFiles/kv.dir/examples/kv.cpp.o
.PHONY : examples/kv.cpp.o

examples/kv.i: examples/kv.cpp.i
.PHONY : examples/kv.i

# target to preprocess a source file
examples/kv.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kv.dir/build.make CMakeFiles/kv.dir/examples/kv.cpp.i
.PHONY : examples/kv.cpp.i

examples/kv.s: examples/kv.cpp.s
.PHONY : examples/kv.s

# target to generate assembly for a file
examples/kv.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kv.dir/build.make CMakeFiles/kv.dir/examples/kv.cpp.s
.PHONY : examples/kv.cpp.s

server/server.o: server/server.cpp.o
.PHONY : server/server.o

# target to build an object file
server/server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/server/server.cpp.o
.PHONY : server/server.cpp.o

server/server.i: server/server.cpp.i
.PHONY : server/server.i

# target to preprocess a source file
server/server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/server/server.cpp.i
.PHONY : server/server.cpp.i

server/server.s: server/server.cpp.s
.PHONY : server/server.s

# target to generate assembly for a file
server/server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/server/server.cpp.s
.PHONY : server/server.cpp.s

src/messages.o: src/messages.cpp.o
.PHONY : src/messages.o

# target to build an object file
src/messages.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniraft.dir/build.make CMakeFiles/miniraft.dir/src/messages.cpp.o
.PHONY : src/messages.cpp.o

src/messages.i: src/messages.cpp.i
.PHONY : src/messages.i

# target to preprocess a source file
src/messages.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniraft.dir/build.make CMakeFiles/miniraft.dir/src/messages.cpp.i
.PHONY : src/messages.cpp.i

src/messages.s: src/messages.cpp.s
.PHONY : src/messages.s

# target to generate assembly for a file
src/messages.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniraft.dir/build.make CMakeFiles/miniraft.dir/src/messages.cpp.s
.PHONY : src/messages.cpp.s

src/raft.o: src/raft.cpp.o
.PHONY : src/raft.o

# target to build an object file
src/raft.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniraft.dir/build.make CMakeFiles/miniraft.dir/src/raft.cpp.o
.PHONY : src/raft.cpp.o

src/raft.i: src/raft.cpp.i
.PHONY : src/raft.i

# target to preprocess a source file
src/raft.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniraft.dir/build.make CMakeFiles/miniraft.dir/src/raft.cpp.i
.PHONY : src/raft.cpp.i

src/raft.s: src/raft.cpp.s
.PHONY : src/raft.s

# target to generate assembly for a file
src/raft.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniraft.dir/build.make CMakeFiles/miniraft.dir/src/raft.cpp.s
.PHONY : src/raft.cpp.s

src/server.o: src/server.cpp.o
.PHONY : src/server.o

# target to build an object file
src/server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniraft.dir/build.make CMakeFiles/miniraft.dir/src/server.cpp.o
.PHONY : src/server.cpp.o

src/server.i: src/server.cpp.i
.PHONY : src/server.i

# target to preprocess a source file
src/server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniraft.dir/build.make CMakeFiles/miniraft.dir/src/server.cpp.i
.PHONY : src/server.cpp.i

src/server.s: src/server.cpp.s
.PHONY : src/server.s

# target to generate assembly for a file
src/server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/miniraft.dir/build.make CMakeFiles/miniraft.dir/src/server.cpp.s
.PHONY : src/server.cpp.s

test/test_raft.o: test/test_raft.cpp.o
.PHONY : test/test_raft.o

# target to build an object file
test/test_raft.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_raft.dir/build.make CMakeFiles/test_raft.dir/test/test_raft.cpp.o
.PHONY : test/test_raft.cpp.o

test/test_raft.i: test/test_raft.cpp.i
.PHONY : test/test_raft.i

# target to preprocess a source file
test/test_raft.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_raft.dir/build.make CMakeFiles/test_raft.dir/test/test_raft.cpp.i
.PHONY : test/test_raft.cpp.i

test/test_raft.s: test/test_raft.cpp.s
.PHONY : test/test_raft.s

# target to generate assembly for a file
test/test_raft.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_raft.dir/build.make CMakeFiles/test_raft.dir/test/test_raft.cpp.s
.PHONY : test/test_raft.cpp.s

test/test_read_write.o: test/test_read_write.cpp.o
.PHONY : test/test_read_write.o

# target to build an object file
test/test_read_write.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_read_write.dir/build.make CMakeFiles/test_read_write.dir/test/test_read_write.cpp.o
.PHONY : test/test_read_write.cpp.o

test/test_read_write.i: test/test_read_write.cpp.i
.PHONY : test/test_read_write.i

# target to preprocess a source file
test/test_read_write.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_read_write.dir/build.make CMakeFiles/test_read_write.dir/test/test_read_write.cpp.i
.PHONY : test/test_read_write.cpp.i

test/test_read_write.s: test/test_read_write.cpp.s
.PHONY : test/test_read_write.s

# target to generate assembly for a file
test/test_read_write.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_read_write.dir/build.make CMakeFiles/test_read_write.dir/test/test_read_write.cpp.s
.PHONY : test/test_read_write.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... bench"
	@echo "... client"
	@echo "... coroio"
	@echo "... echoclient"
	@echo "... echoserver"
	@echo "... echotest"
	@echo "... kv"
	@echo "... miniraft"
	@echo "... resolver"
	@echo "... server"
	@echo "... sslechoclient"
	@echo "... sslechoserver"
	@echo "... test_raft"
	@echo "... test_read_write"
	@echo "... timers"
	@echo "... ut_tests"
	@echo "... client/client.o"
	@echo "... client/client.i"
	@echo "... client/client.s"
	@echo "... examples/kv.o"
	@echo "... examples/kv.i"
	@echo "... examples/kv.s"
	@echo "... server/server.o"
	@echo "... server/server.i"
	@echo "... server/server.s"
	@echo "... src/messages.o"
	@echo "... src/messages.i"
	@echo "... src/messages.s"
	@echo "... src/raft.o"
	@echo "... src/raft.i"
	@echo "... src/raft.s"
	@echo "... src/server.o"
	@echo "... src/server.i"
	@echo "... src/server.s"
	@echo "... test/test_raft.o"
	@echo "... test/test_raft.i"
	@echo "... test/test_raft.s"
	@echo "... test/test_read_write.o"
	@echo "... test/test_read_write.i"
	@echo "... test/test_read_write.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

